export const VIETNAM_UNIVERSITIES = [
  "Đại học Quốc gia Hà Nội",
  "Đại học Quốc gia Thành phố Hồ Chí Minh",
  "Đại học Bách khoa Hà Nội",
  "Đại học Kinh tế Quốc dân",
  "Đại học Ngoại thương",
  "Đại học Y Hà Nội",
  "Đại học Sư phạm Hà Nội",
  "Đại học Luật Hà Nội",
  "Đại học Giao thông Vận tải",
  "Đại học Thủy lợi",
  "Đại học Công nghiệp Hà Nội",
  "Đại học Xây dựng Hà Nội",
  "Đại học Mở Hà Nội",
  "Đại học Thương mại",
  "Đại học Văn hóa Hà Nội",
  "Đại học Mỹ thuật Việt Nam",
  "Đại học Kinh tế Thành phố Hồ Chí Minh",
  "Đại học Bách khoa - ĐHQG TPHCM",
  "Đại học Khoa học Tự nhiên - ĐHQG TPHCM",
  "Đại học Khoa học Xã hội và Nhân văn - ĐHQG TPHCM",
  "Đại học Công nghệ thông tin - ĐHQG TPHCM",
  "Đại học Quốc tế - ĐHQG TPHCM",
  "Đại học Luật Thành phố Hồ Chí Minh",
  "Đại học Sư phạm Thành phố Hồ Chí Minh",
  "Đại học Y Dược Thành phố Hồ Chí Minh",
  "Đại học Tôn Đức Thắng",
  "Đại học RMIT Việt Nam",
  "Đại học FPT",
  "Đại học Cần Thơ",
  "Đại học Huế",
  "Đại học Đà Nẵng",
  "Đại học Thái Nguyên",
  "Đại học Vinh",
  "Đại học Quy Nhơn",
  "Đại học Đà Lạt",
  "Đại học Nha Trang",
  "Trường Đại học Công nghệ (ĐHQG Hà Nội)",
  "Học viện Công nghệ Bưu chính Viễn thông",
  "Học viện Ngân hàng",
  "Học viện Tài chính",
  "Học viện Ngoại giao",
  "Học viện Báo chí và Tuyên truyền",
  "Học viện Nông nghiệp Việt Nam",
  "Trường Đại học Nông Lâm TPHCM",
  "Trường Đại học Công nghiệp TPHCM",
  "Trường Đại học Sư phạm Kỹ thuật TPHCM",
  "Trường Đại học Kiến trúc TPHCM",
  "Trường Đại học Y khoa Phạm Ngọc Thạch",
  "Trường Đại học Sài Gòn",
  "Trường Đại học Hoa Sen",
  "Trường Đại học Văn Lang",
  "Trường Đại học Duy Tân",
  "Trường Đại học Lạc Hồng",
  "Trường Đại học Việt Đức",
  "Đại học VinUniversity",
  "Học viện Quân y",
  "Học viện Kỹ thuật Quân sự",
  "Học viện An ninh nhân dân",
  "Học viện Cảnh sát nhân dân",
  "Trường Cao đẳng FPT Polytechnic",
  "Trường Cao đẳng Kinh tế Đối ngoại",
  "Trường Cao đẳng Công Thương TPHCM",
  "Trường Cao đẳng Viễn Đông",
  "Trường Cao đẳng Kỹ thuật Cao Thắng",
  "Trường Cao đẳng Bách khoa Sài Gòn",
  "Trường Cao đẳng Công nghệ Thủ Đức",
  "Trường Cao đẳng Du lịch Sài Gòn",
  "Trường Cao đẳng Giao thông Vận tải TPHCM",
  "Trường Cao đẳng Công nghệ thông tin TPHCM",
  "Trường Cao đẳng Quốc tế Hà Nội (HIC)",
  "Trường Cao đẳng Y Hà Nội",
  "Trường Cao đẳng nghề Bách khoa Hà Nội (HACTECH)",
  "Trường Cao đẳng Công nghệ cao Hà Nội (HHT)",
  "Trường Cao đẳng Công thương Việt Nam",
  "Trường Cao đẳng Dược Hà Nội",
  "Trường Cao đẳng Thương mại và Du lịch Hà Nội",
  "Trường Cao đẳng Việt Mỹ Hà Nội"
].sort();
